export enum QueryKeys {
  GET_TODOS,
  GET_USERS,
  GET_INFINITE_USERS,
  GET_TEAMS,
  GET_INFINITE_TEAMS,
  GET_DOCUMENTS,
  GET_INFINITE_DOCUMENTS,
  GET_TAGS,
  GET_INFINITE_TAGS,
  GET_ACTION_LOGS,
  GET_INFINITE_ACTION_LOGS,
}
